#!/bin/bash

# assume that we have checkout the same commit on remote; for larger files (here only PDF)
# we synchronize them to our local version, we don't put them in the public history
echo "Pulling papers from remote"
rsync -auvc --delete --prune-empty-dirs --info=progress --include '*.pdf' --include '*/' --exclude "*" arbeit:Note/papers/ papers/
